# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            issykul
tagline:          'issykuls Website'
description:      'Default Description'
url:              http://issykul.github.io
baseurl:          /

author:
  name:           'issykul'
  url:            https://twitter.com/theissykul

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Issykul/issykul.github.io
